version: '3.3'

services:
  drupal:
    image: drupal:latest
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
      - ./drupal/composer.json:/var/www/html/composer.json
      - ./drupal/composer.lock:/var/www/html/composer.lock
      - drupal_trusted_host:"www\.example\.com"
      - drupal_files:./modules/glossary_descritptions
      - drupal_files:./modules/glossary_install
      - drupal_files:./modules/glossary_taxonomy
      - ./modules/glossary_terms
      - ./data/modules/tooltip:/var/www/html/modules/tooltip
      - ./data/modules/glossary:/var/www/html/modules/glossary
    restart: always

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"